version: "1.0"
last_updated: 2025-08-20T00:00:00Z

routing_rules:
  # High-value transactions go to primary processor
  - name: "high_value_transactions"
    priority: 1
    condition_type: "amount_threshold"
    condition_value:
      amount: 1000.0
      operator: "greater_than"
    target_processor: "processor_a"
    percentage: 100
    is_active: true
    description: "Route high-value transactions (>$1000) to primary processor for better success rates"
    created_at: 2025-08-20T00:00:00Z

  # EUR and GBP transactions to multi-currency processor
  - name: "euro_gbp_transactions"
    priority: 2
    condition_type: "currency"
    condition_value:
      currencies: ["EUR", "GBP"]
    target_processor: "processor_b"
    percentage: 100
    is_active: true
    description: "Route EUR/GBP transactions to processor B for better FX rates"
    created_at: 2025-08-20T00:00:00Z

  # Japanese market transactions
  - name: "japan_marketplace"
    priority: 3
    condition_type: "marketplace"
    condition_value:
      marketplaces: ["JP", "japan"]
    target_processor: "processor_b"
    percentage: 100
    is_active: true
    description: "Route Japanese marketplace transactions to processor B"
    created_at: 2025-08-20T00:00:00Z

  # Premium user tier gets primary processor
  - name: "premium_users"
    priority: 4
    condition_type: "user_tier"
    condition_value:
      tiers: ["premium", "enterprise"]
    target_processor: "processor_a"
    percentage: 100
    is_active: true
    description: "Premium users get primary processor for better service"
    created_at: 2025-08-20T00:00:00Z

  # Test client routing
  - name: "test_client_routing"
    priority: 5
    condition_type: "client_id"
    condition_value:
      client_ids: ["test_client_123", "demo_client"]
    target_processor: "processor_b"
    percentage: 100
    is_active: false
    description: "Test client gets routed to processor B (disabled)"
    created_at: 2025-08-20T00:00:00Z

  # Default traffic split - 70% to processor A
  - name: "default_primary_split"
    priority: 10
    condition_type: "percentage"
    condition_value: {}
    target_processor: "processor_a"
    percentage: 70
    is_active: true
    description: "Default 70% traffic to primary processor"
    created_at: 2025-08-20T00:00:00Z

  # Default traffic split - 30% to processor B
  - name: "default_secondary_split"
    priority: 11
    condition_type: "percentage"
    condition_value: {}
    target_processor: "processor_b"
    percentage: 30
    is_active: true
    description: "Default 30% traffic to secondary processor"
    created_at: 2025-08-20T00:00:00Z

# Fallback rule if no others match
default_rule:
  name: "fallback_rule"
  priority: 999
  condition_type: "percentage"
  condition_value: {}
  target_processor: "processor_a"
  percentage: 100
  is_active: true
  description: "Fallback to processor A if no other rules match"